YCDOCIO-3572: Added TF file and readme
yandex-cloud-examples/yc-data-proc-mysql-data-import pull request #1
Opened 2024-05-17 15:28 UTC by Nadezhda-Subotka

https://st.yandex-team.ru/YCDOCIO-3572

Added TF file and readme.

2024-05-24 13:50 UTC, alena-linki requested changes
Внутреннее ревью

2024-05-24 13:50 UTC, alena-linki commented on README.md
> +Утилита [Sqoop](https://yandex.cloud/ru/docs/data-proc/operations/sqoop-usage) позволяет импортировать данные из [Managed Service for MySQL](https://yandex.cloud/ru/docs/managed-mysql) в кластер [Yan
Вводную фразу нельзя заканчивать предлогом.

```suggestion
Утилита [Sqoop](https://yandex.cloud/ru/docs/data-proc/operations/sqoop-usage) позволяет импортировать данные из [Managed Service for MySQL](https://yandex.cloud/ru/docs/managed-mysql) в кластер [Yandex Data Proc](https://yandex.cloud/ru/docs/data-proc). В зависимости от конфигурации кластера Yandex Data Proc вы можете выполнить импорт в одно из следующих хранилищ:
```

2024-05-24 20:02 UTC, Nadezhda-Subotka commented on README.md
> +Утилита [Sqoop](https://yandex.cloud/ru/docs/data-proc/operations/sqoop-usage) позволяет импортировать данные из [Managed Service for MySQL](https://yandex.cloud/ru/docs/managed-mysql) в кластер [Yan
Исправила.

2024-05-28 08:34 UTC, alena-linki approved these changes

2024-06-11 11:12 UTC, lanieuszko approved these changes

2024-06-11 11:19 UTC, merged